---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/auth-type: none
    alb.ingress.kubernetes.io/group.name: default-public
    alb.ingress.kubernetes.io/group.order: "-250"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    net.almacareer.kubernetes.external-dns/source: ignore
  name: {{ template "sonarqube.name" . }}-{{ .Values.istio.virtualservice.name.context }}-{{ .Values.istio.virtualservice.name.purpose }}
  namespace: istio-system
spec:
  ingressClassName: alb
  rules:
  - host: {{ template "sonarqube.name" . }}-{{ .Values.istio.virtualservice.name.context }}-{{ .Values.istio.virtualservice.name.purpose }}.{{ .Values.istio.ingress.url }}
    http:
      paths:
      - backend:
          service:
            name: istio-gateway-public
            port:
              number: 15021
        path: /healthz/ready
        pathType: Exact
      - backend:
          service:
            name: istio-gateway-public
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: {{ .Values.istio.ingress.hostname }}
