---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "sonarqube.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "sonarqube.name" . }}
